apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-memory
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - bookjjeok
    labelSelectors:
      app: backend
  stressors:
    memory:
      workers: 4
      size: '350MiB'
  duration: '5m'